version: '3.4'
services:
    rb-api:
        build:
            context: ../action-bidonvilles-api
            target: development
        container_name: rb_api
        env_file: ./config/.env.sample
        depends_on:
            - rb-database
        ports:
            - "1236:8080"
        networks:
            - rb-network

    rb-database:
        image: postgres:13
        container_name: rb_database
        volumes:
            - rb-pg-data:/var/lib/postgresql/data
        env_file: ./config/.env.sample
        healthcheck:
            test: pg_isready -U postgres -h rb-database
        networks:
            - rb-network

volumes:
    rb-pg-data:

networks:
    rb-network:
        driver: bridge
